FROM golang:1.16
ENV GOPROXY="https://goproxy.cn,direct"


WORKDIR /src
COPY . .

RUN cd nvidia_gpu_logger && go build .

FROM nvcr.io/nvidia/cuda:10.0-base-ubuntu18.04

COPY --from=0 /src/nvidia_gpu_logger/nvidia_gpu_logger .

ENTRYPOINT ["./nvidia_gpu_logger"]