FROM golang:1.16
ENV GOPROXY="https://goproxy.cn,direct"


WORKDIR /src
COPY . .

RUN cd cadvisor_logger && go build .

FROM ubuntu

COPY --from=0 /src/cadvisor_logger/cadvisor_logger .

ENTRYPOINT ["./cadvisor_logger"]